FROM alpine

ARG TARGETPLATFORM
ENV TZ=Asia/Shanghai \
    PUID=10001 \
    PGID=10001

RUN apk add --no-cache alpine-conf ca-certificates su-exec && \
    /usr/sbin/setup-timezone -z Asia/Shanghai && \
    apk del alpine-conf && \
    rm -rf /var/cache/apk/* && \
    mkdir -p /app/data && \
    chown -R 10001:10001 /app

COPY build/docker/${TARGETPLATFORM}/octopus /app/octopus
COPY scripts/dockerfiles/entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

CMD ["/entrypoint.sh"]
